README.md
A comment was added to the readme documentation. This solves issue #3
=> chore(readme): Add test comment

packages/data-monitoring/.editorconfig, packages/data-monitoring/.eslintrc.json, packages/data-monitoring/README.md, packages/data-monitoring/package.json, packages/data-monitoring/src/domains/booking.js, packages/data-monitoring/src/domains/index.js, packages/data-monitoring/src/domains/place.js, packages/data-monitoring/src/domains/user.js, packages/data-monitoring/src/index.js, packages/data-monitoring/src/useCases/booking.js, packages/data-monitoring/src/useCases/index.js, packages/data-monitoring/src/useCases/place.js, packages/data-monitoring/src/useCases/user.js, yarn.lock
I create the data monitoring package in base to requirements in this issue. I appreciate the feedback
Fix #103
=> chore: Create a data-monitoring package [Data monitoring] #103

packages/api-gateway/src/drivers/http/adapters/index.js, packages/api-gateway/src/drivers/http/adapters/notifications/handlers.js, packages/api-gateway/src/drivers/http/routes/notifications/index.js, packages/api-gateway/src/drivers/http/routes/notifications/schema.js
A welcome endpoint responding with a message for the notifications module in the API Gateway
=> Initial integration of notifications module with the API Gateway

packages/notifications-system/.eslintignore, packages/notifications-system/.eslintrc.json, packages/notifications-system/README.md, packages/notifications-system/__tests__/notifications.test.js, packages/notifications-system/jest.config.js, packages/notifications-system/package.json, packages/notifications-system/src/index.js, packages/notifications-system/src/utils/welcomPackage.js
Estructura del repositorio backend del Notifications system
=> Estructura del repositorio backend del Notifications system

.env.example, .gitignore, packages/api-gateway/package.json, packages/api-gateway/src/drivers/http/adapters/index.js, packages/api-gateway/src/drivers/http/adapters/math/handlers.js, packages/api-gateway/src/drivers/http/adapters/places/handlers.js, packages/api-gateway/src/drivers/http/plugins/services.js, packages/api-gateway/src/drivers/http/routes/places/index.js, packages/api-gateway/src/drivers/http/routes/places/schema.js, packages/places/.eslintrc.json, packages/places/README.md, packages/places/__tests__/dbWritter.test.js, packages/places/config/dbcredentials.js, packages/places/config/environment.js, packages/places/jest.config.js, packages/places/package-lock.json, packages/places/package.json, packages/places/src/domains/DataSchema.js, packages/places/src/domains/index.js, packages/places/src/drivers/mysql/connection.js, packages/places/src/index.js, packages/places/src/useCases/dbManagement/dbWriter.js, packages/places/src/useCases/index.js, packages/places/src/utils/logger.js, yarn.lock
=> feat(places): package created

packages/api-gateway/src/drivers/http/routes/places/index.js
=> fix(api-gateway): typo

packages/api-gateway/.eslintrc.js, packages/api-gateway/__tests__/geolocation.test.js, packages/api-gateway/mocks/geolocationServices.mock.js, packages/api-gateway/package.json, packages/api-gateway/src/drivers/http/adapters/admin_panel/handlers.js, packages/api-gateway/src/drivers/http/adapters/geolocation/handlers.js, packages/api-gateway/src/drivers/http/adapters/index.js, packages/api-gateway/src/drivers/http/adapters/math/handlers.js, packages/api-gateway/src/drivers/http/adapters/notifications/handlers.js, packages/api-gateway/src/drivers/http/adapters/places/handlers.js, packages/api-gateway/src/drivers/http/adapters/status/handlers.js, packages/api-gateway/src/drivers/http/plugins/services.js, packages/api-gateway/src/drivers/http/routes/admin_panel/api/index.js, packages/api-gateway/src/drivers/http/routes/geolocation/index.js, packages/api-gateway/src/drivers/http/routes/geolocation/schema.js, packages/api-gateway/src/drivers/http/routes/math/index.js, packages/api-gateway/src/drivers/http/routes/math/schema.js, packages/api-gateway/src/drivers/http/routes/notifications/index.js, packages/api-gateway/src/drivers/http/routes/notifications/schema.js, packages/api-gateway/src/drivers/http/routes/places/index.js, packages/api-gateway/src/drivers/http/routes/places/schema.js, packages/api-gateway/src/drivers/http/routes/status/index.js, packages/api-gateway/src/drivers/http/routes/status/schema.js, packages/api-gateway/src/drivers/http/server.js, packages/api-gateway/src/index.js, yarn.lock
This PR adds eslint config to the api-gateway package.
- Resolves #148 
- Resolves eslint warnings.
=> chore(api-gateway): add eslint to api-gateway

yarn.lock
This PR resolves a git conflict in the yarn.lock file
- Resolves #161 
- Update yarn.lock
=> fix: resolve git conflict in yarn.lock

.commitlintrc.json, .husky/commit-message, .husky/commit-msg, .husky/pre-commit, package.json, packages/messages/__tests__/message.test.js, packages/messages/package.json, packages/messages/src/utils/welcomPackage.js, yarn.lock
This PR adds husky in order to improve the best practices.
- Resolves #151 
- Adds commit message validation.
- Adds pre-commit actions to messages package.
=> chore: add husky

packages/admin-panel/__tests__/userDetail.test.js, packages/admin-panel/__tests__/userStatus.test.js, packages/admin-panel/__tests__/userlist.test.js, packages/admin-panel/mocks/userList.mock.js, packages/admin-panel/src/index.js, packages/admin-panel/src/useCases/index.js, packages/admin-panel/src/useCases/userDetail.js, packages/api-gateway/src/drivers/http/adapters/admin_panel/handlers.js, packages/api-gateway/src/drivers/http/routes/admin-panel/index.js, packages/api-gateway/src/drivers/http/routes/admin-panel/schema.js, yarn.lock
Hi everyone, this is the PR  that resolve #89
I will be waiting for any comment
have a good day
=> feat(userDetail): create user detail endpoint

package.json, packages/data-monitoring/src/drivers/mongodb/connection.js, packages/math/src/drivers/mongodb/connection.js, packages/places/src/useCases/dbManagement/getPlaces.js, yarn.lock
Also I couldn't make git commit because a error appear. I install again husky and commitlint usign the following commands
- yarn add @commitlint/cli @commitlint/cli @commitlint/config-conventional -W
- yarn add husky -W
But I install new version of this packages, I don't know if that can affect our project. I haven't had problems though.
=> fix missing logger imports from places, data-monitoring and math

packages/api-gateway/__tests__/places/deletePlace.test.js, packages/api-gateway/__tests__/places/getPlacesFail.test.js, packages/api-gateway/__tests__/setupTest.js, packages/api-gateway/src/drivers/http/adapters/places/handlers.js, packages/api-gateway/src/drivers/http/routes/places/index.js, packages/api-gateway/src/drivers/http/routes/places/schema.js, packages/math/__tests__/setupTest.js, packages/messages/src/use-cases/list-chat-messages.js, packages/places/.eslintrc.json, packages/places/__tests__/src/domains/MockDataSchema.js, packages/places/__tests__/src/useCases/dbDeleter.test.js, packages/places/__tests__/src/useCases/dbWritter.test.js, packages/places/src/domains/DataSchema.js, packages/places/src/drivers/mysql/connection.js, packages/places/src/index.js, packages/places/src/useCases/dbManagement/dbDeleter.js, packages/places/src/useCases/dbManagement/getPlaces.js, packages/places/src/useCases/index.js
=> feat(api-places): added route for deleting a place

packages/api-gateway/__tests__/places/getPlacesFail.test.js, packages/api-gateway/__tests__/setupTest.js, packages/api-gateway/__tests__/src/drivers/http/routes/chats/get-chat-messages.test.js, packages/api-gateway/src/drivers/http/adapters/messages/handlers.js, packages/api-gateway/src/drivers/http/adapters/users/handlers.js, packages/api-gateway/src/drivers/http/routes/user/index.js, packages/messages/__tests__/setupTest.js, packages/messages/__tests__/src/use-cases/is-chat-related-to-user.test.js, packages/messages/src/index.js, packages/messages/src/use-cases/index.js, packages/messages/src/use-cases/is-chat-related-to-user.js, packages/messages/src/utils/fixtures.js, yarn.lock
This PR adds a new use case to validate chat rooms
- Resolves #177 
- Updates `GET /chats/{id}/messages` endpoint in the `api-gateway`
- Fixes ESLint warnings in the `api-gateway`
=> feat: validate chat room

packages/admin-panel/__tests__/adminById.test.js, packages/admin-panel/src/index.js, packages/admin-panel/src/useCases/adminId.js, packages/admin-panel/src/useCases/index.js, packages/admin-panel/src/utils/fake_data.js, packages/api-gateway/src/drivers/http/adapters/admin_panel/handlers.js, packages/api-gateway/src/drivers/http/routes/admin-panel/index.js, packages/api-gateway/src/drivers/http/routes/admin-panel/schema.js, yarn.lock
Create the get an admin data by id ( ISSUE 86)
=> Feat/admin detail (86)

packages/admin-panel/__tests__/adminById.test.js, packages/admin-panel/__tests__/placeslist.test.js, packages/admin-panel/mocks/placesList.mock.js, packages/admin-panel/src/index.js, packages/admin-panel/src/useCases/adminId.js, packages/admin-panel/src/useCases/index.js, packages/admin-panel/src/useCases/places.js, packages/admin-panel/src/utils/fake_data.js, packages/api-gateway/src/drivers/http/adapters/admin_panel/handlers.js, packages/api-gateway/src/drivers/http/routes/admin-panel/index.js, packages/api-gateway/src/drivers/http/routes/admin-panel/schema.js, yarn.lock
Hi there, this PR Resolves #100 
waiting for your comments
=> feat(admin-panel): adding list places end point

packages/admin-panel/__tests__/userEdit.test.js, packages/admin-panel/src/index.js, packages/admin-panel/src/useCases/index.js, packages/admin-panel/src/useCases/userEdit.js, packages/api-gateway/src/drivers/http/adapters/admin_panel/handlers.js, packages/api-gateway/src/drivers/http/routes/admin-panel/index.js, packages/api-gateway/src/drivers/http/routes/admin-panel/schema.js, packages/api-gateway/src/drivers/http/routes/geolocation/index.js
=> feat: edit an user (90)

packages/admin-panel/__tests__/bookinglist.test.js, packages/admin-panel/__tests__/placeslist.test.js, packages/admin-panel/mocks/bookingsList.mock.js, packages/admin-panel/src/index.js, packages/admin-panel/src/useCases/bookings.js, packages/admin-panel/src/useCases/index.js, packages/api-gateway/src/drivers/http/adapters/admin_panel/handlers.js, packages/api-gateway/src/drivers/http/routes/admin-panel/index.js, packages/api-gateway/src/drivers/http/routes/admin-panel/schema.js, packages/api-gateway/src/drivers/http/routes/geolocation/index.js
Hello Everyone, this is the PR that solves #101 
waiting for your comments
=> Booking list feat

packages/api-gateway/src/drivers/http/server.js, packages/api-gateway/src/drivers/http/utils/swagger.js, yarn.lock
The package had trouble of linting and it got solved with this pr
=> feat(api-gateway): swagger options file and added configuration to the linter

packages/admin-panel/mocks/placesList.mock.js, packages/admin-panel/mocks/userList.mock.js, packages/api-gateway/src/drivers/http/adapters/admin_panel/handlers.js
hello every one, this is a pull request that resolve #187 
waiting for your comments
=> fix(admin-panel): fixing routes for admin-panel

packages/shared/config/environment.js
=> fix(shared): update environment util

packages/user-account/src/domains/db/models/cities.models.js, packages/user-account/src/domains/db/models/emergencyContacts.models.js, packages/user-account/src/domains/db/models/index.js, packages/user-account/src/domains/db/models/places.models.js, packages/user-account/src/domains/db/models/userFavoritePlaces.models.js, packages/user-account/src/index.js, packages/user-account/src/useCases/user.service.js
type correction in sequelizer models
=> Fix(user): sequelizer models

packages/api-gateway/__tests__/src/drivers/http/routes/chats/create-message.test.js, packages/api-gateway/src/drivers/http/adapters/messages/handlers.js, packages/api-gateway/src/drivers/http/routes/chats/index.js, packages/api-gateway/src/drivers/http/routes/chats/schema.js, packages/messages/__tests__/src/use-cases/create-message.test.js, packages/messages/__tests__/src/utils/validator.test.js, packages/messages/src/index.js, packages/messages/src/use-cases/create-message.js, packages/messages/src/use-cases/index.js, packages/messages/src/utils/validator.js
This pr adds an endpoint to create messages into a chat room.
- Resolves #10 
- Websocket events will be added in another PR
- Authentication will be added in another PR
=> feat(ISSUE-10): create message

packages/api-gateway/src/drivers/http/adapters/messages/handlers.js, packages/api-gateway/src/drivers/http/routes/chats/schema.js
adds user id query param to messages endpoints 
- Resolves #253
=> feat(api-gateway): add userId query param to messages endpoints

packages/admin-panel/__tests__/adminEdit.test.js, packages/admin-panel/__tests__/userEdit.test.js, packages/admin-panel/src/index.js, packages/admin-panel/src/useCases/adminEdit.js, packages/admin-panel/src/useCases/index.js, packages/api-gateway/src/drivers/http/adapters/admin-panel/handlers.js, packages/api-gateway/src/drivers/http/routes/admin-panel/index.js, packages/api-gateway/src/drivers/http/routes/admin-panel/schema.js
We need to create an endpoint with the ability to edit admin information.
=> feat: admin edit

packages/user-account/src/domains/db/migrations/20220429175632-createUserSchema.js, packages/user-account/src/domains/db/migrations/20220505193222-createEmergencyContactsSchema.js, packages/user-account/src/domains/db/migrations/20220506185011-createUserFavoritePlacesSchema.js, packages/user-account/src/domains/db/migrations/20220506185601-createPlacesSchema.js, packages/user-account/src/domains/db/models/emergencyContacts.models.js, packages/user-account/src/domains/db/models/places.models.js, packages/user-account/src/domains/db/models/user.models.js, packages/user-account/src/domains/db/models/userFavoritePlaces.models.js
=> fix(user) : update variables in models and migrations 

packages/api-gateway/src/drivers/http/adapters/users/bookmarkServices/getBookmark.js, packages/api-gateway/src/drivers/http/adapters/users/handlers.js, packages/api-gateway/src/drivers/http/routes/user/index.js, packages/api-gateway/src/drivers/http/routes/user/schema/bookmark/getBookmarkSchema.js, packages/api-gateway/src/drivers/http/routes/user/schema/index.js, packages/user-account/src/index.js, packages/user-account/src/useCases/bookmark.service.js
this PR adds the feat of fetching the data of a bookmark by its ID
=> Feat(user) new endpoint GET '/user/:userId/bookmark/:bookmarkId/

packages/geolocation/__tests__/geocoding.test.js, packages/geolocation/__tests__/reverseGeocoding.test.js, packages/geolocation/package.json, packages/geolocation/src/domains/index.js, packages/geolocation/src/domains/places.js, packages/geolocation/src/drivers/nodeGeocoder/connections.js, packages/geolocation/src/index.js, packages/geolocation/src/useCases/index.js, packages/geolocation/src/useCases/places.js, packages/geolocation/src/utils/constants.js, yarn.lock
Methods for geocoding and reversegeocoding, This solve issue #249
=> Feat: geocoding and reverse geocoding

packages/api-gateway/src/drivers/http/adapters/users/bookmarkServices/getBookmarkList.js, packages/api-gateway/src/drivers/http/adapters/users/bookmarkServices/updateBookmark.js, packages/api-gateway/src/drivers/http/adapters/users/handlers.js, packages/api-gateway/src/drivers/http/routes/user/index.js, packages/api-gateway/src/drivers/http/routes/user/schema/bookmark/getBookmarkListSchema.js, packages/api-gateway/src/drivers/http/routes/user/schema/bookmark/updateBookmarkSchema.js, packages/api-gateway/src/drivers/http/routes/user/schema/index.js, packages/user-account/src/index.js, packages/user-account/src/useCases/bookmark.service.js
new endpoints
- `GET` /user/:userId/bookmarks
- `PUT` /user/:userId/bookmark/:bookmarkId
=> feat(user): new endpoints in bookmark GET & PUT

.gitignore, packages/api-gateway/src/drivers/http/adapters/geolocation/handlers.js, packages/api-gateway/src/drivers/http/routes/geolocation/schema.js, packages/geolocation/src/domains/index.js, packages/geolocation/src/domains/places.js, packages/geolocation/src/index.js, packages/geolocation/src/useCases/index.js, packages/geolocation/src/useCases/places.js
=> feat: Method to create a place in geolocation database
